### ISSUE TITLE
Password contains '/' gives error.

### ISSUE THREAD

**Issue by YoungjaeKim** [delano/redis-dump#16]
Thanks for the good utility.

When password contains `/` character, it gives below error.

`ERROR (URI::InvalidURIError): the scheme redis does not accept registry part: :Nwb8BFqt0fbP (or bad hostname?)`

I want to fix by myself but I'm new to Ruby. sorry.

**Comment by delano** [comment]
Fixed in 0.4.0. You can now include the password as an argument. 

    $ redis-dump -u localhost:6379 -a 'some/password'
