### ISSUE TITLE
`redis-load` has some problems executing `sadd`

### ISSUE THREAD

**Issue by cclever7** [delano/redis-dump#35]
hi, when I execute the command `cat [*.json] | redis-load -u [host]/[db_index] -a [passwd]`,
"sadd" seems problematic. See details from the image below
I'm new to ruby, can you help me with this problem? or tell me why output these
![image](https://user-images.githubusercontent.com/21021576/231444219-4a10572a-561b-45af-9e90-3623a7082284.png)

**Comment by delano** [comment]
Thanks for the report.

This issue is fixed as of [0.6.0](https://github.com/delano/redis-dump/releases/latest) (which now support redis-rb 5 as well).
